server :
  port : 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true
        trace: false

  datasource:
    url: jdbc:h2:file:./src/main/resources/DB
    username: team20
    password:
    database-platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver