server :
  port : 9000

spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:file:./src/main/resources/DB
    username: team20
    password:
    driverClassName: org.h2.Driver